# Dependabot Configuration
# https://docs.github.com/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "github-actions"  # zizmor: ignore[dependabot-cooldown]
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "pip"  # zizmor: ignore[dependabot-cooldown]
  directory: "/"
  schedule:
    interval: "daily"
